// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: quake/key.proto

package quake

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// for Kafka message keys.
type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	QuakeID string `protobuf:"bytes,1,opt,name=quake_iD,json=quakeID,proto3" json:"quake_iD,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_quake_key_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_quake_key_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_quake_key_proto_rawDescGZIP(), []int{0}
}

func (x *Key) GetQuakeID() string {
	if x != nil {
		return x.QuakeID
	}
	return ""
}

var File_quake_key_proto protoreflect.FileDescriptor

var file_quake_key_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x2f, 0x6b, 0x65, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x22, 0x20, 0x0a, 0x03, 0x4b, 0x65, 0x79, 0x12,
	0x19, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x5f, 0x69, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x71, 0x75, 0x61, 0x6b, 0x65, 0x49, 0x44, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b,
	0x71, 0x75, 0x61, 0x6b, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_quake_key_proto_rawDescOnce sync.Once
	file_quake_key_proto_rawDescData = file_quake_key_proto_rawDesc
)

func file_quake_key_proto_rawDescGZIP() []byte {
	file_quake_key_proto_rawDescOnce.Do(func() {
		file_quake_key_proto_rawDescData = protoimpl.X.CompressGZIP(file_quake_key_proto_rawDescData)
	})
	return file_quake_key_proto_rawDescData
}

var file_quake_key_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_quake_key_proto_goTypes = []interface{}{
	(*Key)(nil), // 0: quake.Key
}
var file_quake_key_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_quake_key_proto_init() }
func file_quake_key_proto_init() {
	if File_quake_key_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_quake_key_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_quake_key_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_quake_key_proto_goTypes,
		DependencyIndexes: file_quake_key_proto_depIdxs,
		MessageInfos:      file_quake_key_proto_msgTypes,
	}.Build()
	File_quake_key_proto = out.File
	file_quake_key_proto_rawDesc = nil
	file_quake_key_proto_goTypes = nil
	file_quake_key_proto_depIdxs = nil
}
